export const TARGET_TITLES: Record<string, string> = {
    PENSION: 'Пассивный доход в будущем',
    EDUCATION_V2021_09: 'Образование детей',
    HEALTH: 'Защита здоровья',
    INVESTMENT: 'Инвестиции',
    CAPITAL_MULTIPLICATION: 'Накопить капитал',
    APARTMENT: 'Квартира',
    HOUSE: 'Загородная недвижимость',
    RENT: 'Рентный доход',
    SAVE_CAPITAL: 'Защитить Капитал',
    LOAN_REFINANCING: 'Рефинансирование кредитов',
    OWN_BUSINESS: 'Собственный бизнес',
    STATE_PENSION: 'Гос. пенсия',
    FIN_RESERVE: 'Финансовый резерв',
    RESERVE: 'Финансовый резерв',
    OTHER: 'Другая цель',
    MORTGAGE: 'Ипотека',
    'OTHER$AUTO': 'Автомобиль',
    'OTHER$MOVE': 'Переезд',
    'OTHER$TRAVEL': 'Путешествие',
    'OTHER$FIN_RESERVE': 'Финансовый резерв',
    'OTHER$MORTGAGE_INITIAL': 'Первый взнос на ипотеку',
    'OTHER$EDUCATION_APARTMENT': 'Образование + Квартира',
    'OTHER$EDUCATION_AUTO': 'Образование + Авто',
    'OTHER$CAPITAL': 'Сохранить капитал',
    'MORTGAGE$HOUSE': 'Ипотека на дом',
    'MORTGAGE$APARTMENT': 'Ипотека на квартиру',
    'MORTGAGE$CASH': 'Ипотечный кредит',
    'MORTGAGE$REFINANCE': 'Рефинансирование ипотеки',
    'MORTGAGE$AUTO': 'Автокредит',
    TAX_PLANNING: 'Налоговое планирование',
};

export const RISK_PROFILE_LABELS: Record<string, string> = {
    CONSERVATIVE: 'Консервативный',
    BALANCED: 'Сбалансированный',
    AGGRESSIVE: 'Агрессивный',
    SUPER_AGGRESSIVE: 'Сверхагрессивный',
};

export const TargetTypeEnum = {
    Pension: 'PENSION',
    EducationV202109: 'EDUCATION_V2021_09',
    Health: 'HEALTH',
    Investment: 'INVESTMENT',
    CapitalMultiplication: 'CAPITAL_MULTIPLICATION',
    Apartment: 'APARTMENT',
    House: 'HOUSE',
    Rent: 'RENT',
    SaveCapital: 'SAVE_CAPITAL',
    LoanRefinancing: 'LOAN_REFINANCING',
    OwnBusiness: 'OWN_BUSINESS',
    StatePension: 'STATE_PENSION',
    FinReserve: 'FIN_RESERVE',
    Other: 'OTHER',
    Mortgage: 'MORTGAGE',
    OtherAuto: 'OTHER$AUTO',
    OtherMove: 'OTHER$MOVE',
    OtherTravel: 'OTHER$TRAVEL',
    OtherFinReserve: 'OTHER$FIN_RESERVE',
    OtherMortgageInitial: 'OTHER$MORTGAGE_INITIAL',
    OtherEducationApartment: 'OTHER$EDUCATION_APARTMENT',
    OtherEducationAuto: 'OTHER$EDUCATION_AUTO',
    OtherCapital: 'OTHER$CAPITAL',
    MortgageHouse: 'MORTGAGE$HOUSE',
    MortgageApartment: 'MORTGAGE$APARTMENT',
    MortgageCash: 'MORTGAGE$CASH',
    MortgageRefinance: 'MORTGAGE$REFINANCE',
    MortgageAuto: 'MORTGAGE$AUTO',
    TaxPlanning: 'TAX_PLANNING',
} as const;
